=== theRenard/Test_DLtk/assets/Scripts/data_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/LDtk",
  "definitions": {
      "LDtk": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "identifier": {
                  "type": "string"
              },
              "uniqueIdentifer": {
                  "type": "string",
                  "format": "uuid"
              },
              "x": {
                  "type": "integer"
              },
              "y": {
                  "type": "integer"
              },
              "width": {
                  "type": "integer"
              },
              "height": {
                  "type": "integer"
              },
              "bgColor": {
                  "type": "string"
              },
              "neighbourLevels": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/NeighbourLevel"
                  }
              },
              "customFields": {
                  "$ref": "#/definitions/LDtkCustomFields"
              },
              "layers": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
              },
              "entities": {
                  "$ref": "#/definitions/Entities"
              }
          },
          "required": [
              "customFields",
              "entities",
              "height",
              "identifier",
              "layers",
              "neighbourLevels",
              "uniqueIdentifer",
              "width",
              "x",
              "y"
          ],
          "title": "LDtk"
      },
      "LDtkCustomFields": {
          "type": "object",
          "additionalProperties": false,
          "title": "LDtkCustomFields"
      },
      "Entities": {
          "type": "object",
          "additionalProperties": true,
          "patternProperties": {
              "^.*$": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/Entity"
                  }
              }
          },
          "title": "Entities"
      },
      "Entity": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "id": {
                  "type": "string"
              },
              "iid": {
                  "type": "string",
                  "format": "uuid"
              },
              "layer": {
                  "type": "string"
              },
              "x": {
                  "type": "integer"
              },
              "y": {
                  "type": "integer"
              },
              "width": {
                  "type": "integer"
              },
              "height": {
                  "type": "integer"
              },
              "color": {
                  "type": "integer"
              },
              "customFields": {
                  "$ref": "#/definitions/EntityCustomFields"
              }
          },
          "required": [
              "color",
              "customFields",
              "height",
              "id",
              "iid",
              "layer",
              "width",
              "x",
              "y"
          ],
          "title": "Entity"
      },
      "EntityCustomFields": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
              "items": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
              }
          },
          "required": [
              "items"
          ],
          "title": "EntityCustomFields"
      },
      "NeighbourLevel": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "levelIid": {
                  "type": "string",
                  "format": "uuid"
              },
              "dir": {
                  "type": "string"
              }
          },
          "required": [
              "dir",
              "levelIid"
          ],
          "title": "NeighbourLevel"
      }
  }
}

=== theRenard/Test_DLtk/assets/LDtk/Example/simplified/Your_typical_2D_platformer/data.json
{
	"identifier": "Your_typical_2D_platformer",
	"uniqueIdentifer": "a315ac10-66b0-11ec-9cd7-99f223ad6ade",
	"x": 0,
	"y": 0,
	"width": 848,
	"height": 336,
	"bgColor": "#50506A",
	"neighbourLevels": [
		{
			"levelIid": "a316bd80-66b0-11ec-9cd7-c50cdc9d2cc4",
			"dir": "n"
		},
		{
			"levelIid": "a317cef0-66b0-11ec-9cd7-dd2f249c8c8b",
			"dir": "s"
		}
	],
	"customFields" : {},
	"layers": [
		"Bg_textures.png",
		"Collisions.png",
		"Wall_shadows.png"
	],
	"entities": {
		"Player": [
			{
				"id": "Player",
				"iid": "a315d323-66b0-11ec-9cd7-8ddce09157bc",
				"layer": "Entities",
				"x": 184,
				"y": 208,
				"width": 24,
				"height": 24,
				"color": 11009828,
				"customFields": {
					"items": [
						"Knife",
						"Boots"
					]
				}
			}
		],
		"Chest": [
			{
				"id": "Chest",
				"iid": "a315d324-66b0-11ec-9cd7-0d0128b37734",
				"layer": "Entities",
				"x": 504,
				"y": 288,
				"width": 32,
				"height": 24,
				"color": 7003628,
				"customFields": {
					"content": [
						"Healing_Plant",
						"Water",
						"Meat"
					]
				}
			}
		],
		"Mob": [
			{
				"id": "Mob",
				"iid": "a315d325-66b0-11ec-9cd7-f9e1c56d6020",
				"layer": "Entities",
				"x": 328,
				"y": 160,
				"width": 20,
				"height": 20,
				"color": 16711680,
				"customFields": {
					"patrol": [
						{
							"cx": 32,
							"cy": 9
						}
					],
					"loot": [
						"Meat"
					]
				}
			},
			{
				"id": "Mob",
				"iid": "a315d326-66b0-11ec-9cd7-cf3ea20f8dff",
				"layer": "Entities",
				"x": 264,
				"y": 288,
				"width": 20,
				"height": 20,
				"color": 16711680,
				"customFields": {
					"patrol": [
						{
							"cx": 26,
							"cy": 17
						}
					],
					"loot": []
				}
			},
			{
				"id": "Mob",
				"iid": "6abe6740-7820-11ed-b9f3-df5bd7818ec4",
				"layer": "Entities",
				"x": 728,
				"y": 144,
				"width": 20,
				"height": 20,
				"color": 16711680,
				"customFields": {
					"patrol": [
						{
							"cx": 39,
							"cy": 8
						}
					],
					"loot": []
				}
			},
			{
				"id": "Mob",
				"iid": "d19bc690-c640-11ed-92ab-9f600e5064fd",
				"layer": "Entities",
				"x": 344,
				"y": 96,
				"width": 16,
				"height": 16,
				"color": 16711680,
				"customFields": {
					"patrol": [
						{
							"cx": 27,
							"cy": 5
						},
						{
							"cx": 29,
							"cy": 4
						},
						{
							"cx": 32,
							"cy": 4
						},
						{
							"cx": 33,
							"cy": 5
						},
						{
							"cx": 39,
							"cy": 5
						},
						{
							"cx": 40,
							"cy": 4
						},
						{
							"cx": 45,
							"cy": 4
						}
					],
					"loot": []
				}
			}
		],
		"Door": [
			{
				"id": "Door",
				"iid": "a315d327-66b0-11ec-9cd7-35c28e76b04b",
				"layer": "Entities",
				"x": 440,
				"y": 288,
				"width": 12,
				"height": 32,
				"color": 12036218,
				"customFields": {
					"locked": false
				}
			},
			{
				"id": "Door",
				"iid": "a315d328-66b0-11ec-9cd7-c30477cb5ff1",
				"layer": "Entities",
				"x": 568,
				"y": 128,
				"width": 12,
				"height": 48,
				"color": 12036218,
				"customFields": {
					"locked": false
				}
			}
		]
	}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_2/data.json
{
	"identifier": "Level_2",
	"uniqueIdentifer": "b3f7dfe0-c640-11ed-b889-4bdc59cec5f1",
	"x": 896,
	"y": 0,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk/Example/simplified/Bottom/data.json
{
	"identifier": "Bottom",
	"uniqueIdentifer": "a317cef0-66b0-11ec-9cd7-dd2f249c8c8b",
	"x": 80,
	"y": 336,
	"width": 464,
	"height": 256,
	"bgColor": "#50506A",
	"neighbourLevels": [
		{
			"levelIid": "a315ac10-66b0-11ec-9cd7-99f223ad6ade",
			"dir": "n"
		}
	],
	"customFields" : {},
	"layers": [
		"Bg_textures.png",
		"Collisions.png",
		"Wall_shadows.png"
	],
	"entities": {
		"Mob": [
			{
				"id": "Mob",
				"iid": "a317cef6-66b0-11ec-9cd7-a5ccf047f66e",
				"layer": "Entities",
				"x": 312,
				"y": 176,
				"width": 20,
				"height": 20,
				"color": 16711680,
				"customFields": {
					"patrol": [
						{
							"cx": 11,
							"cy": 10
						}
					],
					"loot": [
						"Healing_Plant"
					]
				}
			}
		]
	}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_9/data.json
{
	"identifier": "Level_9",
	"uniqueIdentifer": "35f6d5f0-c640-11ed-b889-f12c4e47ccbc",
	"x": 896,
	"y": 224,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_8/data.json
{
	"identifier": "Level_8",
	"uniqueIdentifer": "1b5e5d30-c640-11ed-b889-ff316a9cc938",
	"x": 672,
	"y": 224,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_11/data.json
{
	"identifier": "Level_11",
	"uniqueIdentifer": "615d85e0-c640-11ed-b889-e9598c4c8916",
	"x": 1344,
	"y": 224,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk/Example/simplified/Top/data.json
{
	"identifier": "Top",
	"uniqueIdentifer": "a316bd80-66b0-11ec-9cd7-c50cdc9d2cc4",
	"x": 352,
	"y": -352,
	"width": 672,
	"height": 352,
	"bgColor": "#50506A",
	"neighbourLevels": [
		{
			"levelIid": "a315ac10-66b0-11ec-9cd7-99f223ad6ade",
			"dir": "s"
		}
	],
	"customFields" : {},
	"layers": [
		"Bg_textures.png",
		"Collisions.png",
		"Wall_shadows.png"
	],
	"entities": {
		"Mob": [
			{
				"id": "Mob",
				"iid": "a316bd86-66b0-11ec-9cd7-837d4383ebc8",
				"layer": "Entities",
				"x": 456,
				"y": 240,
				"width": 20,
				"height": 20,
				"color": 16711680,
				"customFields": {
					"patrol": [
						{
							"cx": 22,
							"cy": 14
						}
					],
					"loot": []
				}
			},
			{
				"id": "Mob",
				"iid": "a316bd87-66b0-11ec-9cd7-df8b07359531",
				"layer": "Entities",
				"x": 424,
				"y": 336,
				"width": 20,
				"height": 20,
				"color": 16711680,
				"customFields": {
					"patrol": [
						{
							"cx": 23,
							"cy": 20
						}
					],
					"loot": []
				}
			},
			{
				"id": "Mob",
				"iid": "a316bd88-66b0-11ec-9cd7-cbd4e685a38f",
				"layer": "Entities",
				"x": 200,
				"y": 224,
				"width": 48,
				"height": 48,
				"color": 16711680,
				"customFields": {
					"patrol": [],
					"loot": [
						"Knife",
						"Healing_Plant"
					]
				}
			}
		],
		"Door": [
			{
				"id": "Door",
				"iid": "a316bd89-66b0-11ec-9cd7-69448da578ed",
				"layer": "Entities",
				"x": 328,
				"y": 224,
				"width": 12,
				"height": 64,
				"color": 12036218,
				"customFields": {
					"locked": false
				}
			},
			{
				"id": "Door",
				"iid": "a316bd8b-66b0-11ec-9cd7-27e78e24a888",
				"layer": "Entities",
				"x": 120,
				"y": 144,
				"width": 12,
				"height": 32,
				"color": 12036218,
				"customFields": {
					"locked": true
				}
			}
		],
		"Chest": [
			{
				"id": "Chest",
				"iid": "a316bd8a-66b0-11ec-9cd7-a986f709d9f8",
				"layer": "Entities",
				"x": 72,
				"y": 160,
				"width": 24,
				"height": 24,
				"color": 7003628,
				"customFields": {
					"content": [
						"Gem",
						"Gem"
					]
				}
			}
		]
	}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_4/data.json
{
	"identifier": "Level_4",
	"uniqueIdentifer": "85e2e360-c640-11ed-b889-bf18c556acca",
	"x": 1344,
	"y": 0,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}
