=== theRenard/Test_DLtk/assets/Scripts/data_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/LDtk",
  "definitions": {
      "LDtk": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "identifier": {
                  "type": "string"
              },
              "uniqueIdentifer": {
                  "type": "string",
                  "format": "uuid"
              },
              "x": {
                  "type": "integer"
              },
              "y": {
                  "type": "integer"
              },
              "width": {
                  "type": "integer"
              },
              "height": {
                  "type": "integer"
              },
              "bgColor": {
                  "type": "string"
              },
              "neighbourLevels": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/NeighbourLevel"
                  }
              },
              "customFields": {
                  "$ref": "#/definitions/LDtkCustomFields"
              },
              "layers": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
              },
              "entities": {
                  "$ref": "#/definitions/Entities"
              }
          },
          "required": [
              "customFields",
              "entities",
              "height",
              "identifier",
              "layers",
              "neighbourLevels",
              "uniqueIdentifer",
              "width",
              "x",
              "y"
          ],
          "title": "LDtk"
      },
      "LDtkCustomFields": {
          "type": "object",
          "additionalProperties": false,
          "title": "LDtkCustomFields"
      },
      "Entities": {
          "type": "object",
          "additionalProperties": true,
          "patternProperties": {
              "^.*$": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/Entity"
                  }
              }
          },
          "title": "Entities"
      },
      "Entity": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "id": {
                  "type": "string"
              },
              "iid": {
                  "type": "string",
                  "format": "uuid"
              },
              "layer": {
                  "type": "string"
              },
              "x": {
                  "type": "integer"
              },
              "y": {
                  "type": "integer"
              },
              "width": {
                  "type": "integer"
              },
              "height": {
                  "type": "integer"
              },
              "color": {
                  "type": "integer"
              },
              "customFields": {
                  "$ref": "#/definitions/EntityCustomFields"
              }
          },
          "required": [
              "color",
              "customFields",
              "height",
              "id",
              "iid",
              "layer",
              "width",
              "x",
              "y"
          ],
          "title": "Entity"
      },
      "EntityCustomFields": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
              "items": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
              }
          },
          "required": [
              "items"
          ],
          "title": "EntityCustomFields"
      },
      "NeighbourLevel": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "levelIid": {
                  "type": "string",
                  "format": "uuid"
              },
              "dir": {
                  "type": "string"
              }
          },
          "required": [
              "dir",
              "levelIid"
          ],
          "title": "NeighbourLevel"
      }
  }
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_1/data.json
{
	"identifier": "Level_1",
	"uniqueIdentifer": "b0715130-c640-11ed-b889-ad3385c5253f",
	"x": 672,
	"y": 0,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_14/data.json
{
	"identifier": "Level_14",
	"uniqueIdentifer": "bde5af00-c640-11ed-b889-91ab422981bb",
	"x": 448,
	"y": 448,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_10/data.json
{
	"identifier": "Level_10",
	"uniqueIdentifer": "580b0c60-c640-11ed-b889-f985e5ed927f",
	"x": 1120,
	"y": 224,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_5/data.json
{
	"identifier": "Level_5",
	"uniqueIdentifer": "a45bcaa0-c640-11ed-b889-d76408c34894",
	"x": 1568,
	"y": 0,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_12/data.json
{
	"identifier": "Level_12",
	"uniqueIdentifer": "ba720c14-c640-11ed-b889-1fd0084f11dd",
	"x": 1568,
	"y": 224,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_6/data.json
{
	"identifier": "Level_6",
	"uniqueIdentifer": "b8639e73-c640-11ed-b889-a1a15ba4aa3d",
	"x": 1792,
	"y": 0,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_7/data.json
{
	"identifier": "Level_7",
	"uniqueIdentifer": "11f4d940-c640-11ed-b889-8d9dab1180ec",
	"x": 448,
	"y": 224,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}

=== theRenard/Test_DLtk/assets/LDtk_Examples/Level_0/data.json
{
	"identifier": "Level_0",
	"uniqueIdentifer": "3f943c70-9f30-11ed-95b7-e9fada14ed55",
	"x": 448,
	"y": 0,
	"width": 160,
	"height": 160,
	"bgColor": "#696A79",
	"neighbourLevels": [],
	"customFields" : {},
	"layers": [
		"Background.png",
		"Platforms.png",
		"Spikes.png",
		"Ladders.png"
	],
	"entities" : {}
}
